name: Build and Zip JAR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build shadowJar

      - name: Zip the JAR
        run: zip -r DailyShop.zip build/libs/*.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-jar
          path: DailyShop.zip
